### ISSUE TITLE
Cannot compile in Xcode version 7.2 and Swift 2.  Module 'libxmlSimu' not found, 'CocoaAsyncSocket/GCDAsyncSocket.h' file not found, Failed to import bridging header.

### ISSUE THREAD

**Issue by jessjpj** [nemesit/SwiftXMPP#11]
HI,
   I am having lots of issues when compiling in latest Swift version, Swift 2 and Xcode 7.2
![screen shot 2015-12-16 at 12 06 43 pm](https://cloud.githubusercontent.com/assets/8969855/11833937/c4e2bdf4-a3ed-11e5-9954-b7f763879c07.png)
1. In DDXMLNode.h
- Module 'libxmlSimu' not found
- Use of undeclared identifier 'XML_DOCUMENT_NODE'
- Use of undeclared identifier 'XML_ELEMENT_NODE'
- Use of undeclared identifier 'XML_ATTRIBUTE_NODE'
- Use of undeclared identifier 'XML_NAMESPACE_DECL'
- Use of undeclared identifier 'XML_PI_NODE'
- Use of undeclared identifier 'XML_COMMENT_NODE'
- Use of undeclared identifier 'XML_TEXT_NODE'
- Use of undeclared identifier 'XML_DTD_NODE'
- Use of undeclared identifier 'XML_ENTITY_DECL'
- Use of undeclared identifier 'XML_ATTRIBUTE_DECL'
- Use of undeclared identifier 'XML_ELEMENT_DECL'
- Use of undeclared identifier 'XML_NOTATION_NODE'
  ![screen shot 2015-12-16 at 12 16 02 pm](https://cloud.githubusercontent.com/assets/8969855/11834053/de8415fe-a3ee-11e5-9d9b-f571263f5658.png)
1. In XMPPStream.h
   - 'CocoaAsyncSocket/GCDAsyncSocket.h' file not found
     ![screen shot 2015-12-16 at 12 16 51 pm](https://cloud.githubusercontent.com/assets/8969855/11834064/f57601dc-a3ee-11e5-84a3-dcc13f0e06e4.png)
2. Failed to import bridging header       '/Users/irismac/Desktop/codes/xmppchat/SwiftXMPP/SwiftXMPP/SwiftXMPP-Bridging-Header.h'
